# Generated by Django 4.2.30 on 2026-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_historicalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], default='ONLINE', max_length=20),
        ),
    ]
