# Generated by Django 4.2.30 on 2026-05-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_historicalorder_payment_method_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customization_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_logos/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customization_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_logos/'),
        ),
    ]
