# Generated by Django 4.2.30 on 2026-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartitem_customization_data_cartitem_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='customization_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customization_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
