# Generated by Django 4.2.30 on 2026-05-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_historicalorder_status_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_logos/')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cart_logos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='orders.cartitem')),
            ],
        ),
    ]
