# Generated by Django 4.2.30 on 2026-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customization_config',
            field=models.JSONField(blank=True, help_text='JSON data for customization zones (coordinates, font, etc.)', null=True),
        ),
    ]
