# Generated by Django 4.2.30 on 2026-04-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_customization_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customization_config',
            field=models.TextField(blank=True, help_text='JSON string for customization zones (coordinates, font, etc.)', null=True),
        ),
    ]
