# Generated by Django 4.2.30 on 2026-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_customization_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_bulk_only',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Weight in KG', max_digits=5),
        ),
    ]
