# Generated by Django 4.2.30 on 2026-04-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_is_bulk_only_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_color',
            field=models.CharField(default='#D91656', help_text='Hex code or Tailwind color name', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, help_text='e.g. NEW, 50% OFF, BESTSELLER', max_length=50, null=True),
        ),
    ]
