# Generated by Django 4.2.30 on 2026-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_badge_color_product_badge_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bulk_only',
            field=models.BooleanField(default=False, help_text='If True, product is only available for bulk orders'),
        ),
    ]
