# Generated by Django 4.2.30 on 2026-05-01 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_product_is_bulk_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.TextField(max_length=100)),
                ('customization_config', models.TextField(blank=True, help_text='JSON string for customization zones (coordinates, font, etc.)', null=True)),
                ('stock', models.IntegerField(default=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0.5, help_text='Weight in KG', max_digits=5)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_bulk_only', models.BooleanField(default=False, help_text='If True, product is only available for bulk orders')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. NEW, 50% OFF, BESTSELLER', max_length=50, null=True)),
                ('badge_color', models.CharField(default='#D91656', help_text='Hex code or Tailwind color name', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
