# Generated by Django 4.2.30 on 2026-05-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_historicalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='customization_config',
            field=models.TextField(default='[]', help_text='JSON string for customization zones (coordinates, font, etc.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_config',
            field=models.TextField(default='[]', help_text='JSON string for customization zones (coordinates, font, etc.)'),
        ),
    ]
