# Generated by Django 4.2.30 on 2026-05-01 12:00

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_historicalproduct_customization_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='customization_config',
            field=models.TextField(default=products.models.default_customization_config, help_text='JSON structure for customization zones (coordinates, font, etc.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_config',
            field=models.TextField(default=products.models.default_customization_config, help_text='JSON structure for customization zones (coordinates, font, etc.)'),
        ),
    ]
