# Generated by Django 4.2.30 on 2026-05-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_historicalproduct_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.CharField(help_text='Path to image relative to static (e.g. products/pen.png)', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(help_text='Path to image relative to static (e.g. products/pen.png)', max_length=255),
        ),
    ]
