# Generated by Django 4.2.30 on 2026-05-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_historicalproduct_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='image_file',
            field=models.TextField(blank=True, help_text='Upload a new product image (overrides static path)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a new product image (overrides static path)', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.CharField(blank=True, help_text='Path to image relative to static (e.g. products/pen.png)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Path to image relative to static (e.g. products/pen.png)', max_length=255, null=True),
        ),
    ]
