# Generated by Django 4.2.30 on 2026-05-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_historicalproduct_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.CharField(blank=True, help_text='Default image path (e.g. products/pen.png)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image_file',
            field=models.TextField(blank=True, help_text='Upload default image', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Default image path (e.g. products/pen.png)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload default image', null=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, help_text='Path to variant image (e.g. products/pen_blue.png)', max_length=255, null=True)),
                ('image_file', models.ImageField(blank=True, help_text='Upload variant image', null=True, upload_to='products/variants/')),
                ('stock', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
