# Generated by Django 4.2.30 on 2026-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_historicalproduct_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='review_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
