<<<<<<< HEAD
# Generated by Django 4.2.30 on 2026-05-11 04:33
=======
# Generated by Django 4.2.30 on 2026-05-12 13:36
>>>>>>> 03bc021 (Updated customization zones)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_attribute_brand_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
