# Generated by Django 4.2.30 on 2026-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_brand_category_parent_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='key_features',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of bullet points'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='specifications',
            field=models.TextField(blank=True, default='{}', help_text='JSON structured technical details'),
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of bullet points'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default='{}', help_text='JSON structured technical details'),
        ),
    ]
